### ISSUE TITLE
Auto login upon new user creation

### ISSUE THREAD

**Issue by pppetrov** [Project-3-WDI/trippy#12]
We are trying to get our users to be automatically logged in when they create their accounts. A simple redirect_to the create session controller (sessions#create) can't work, because redirect cannot be a post (as per HTML 1.1 specs). 

We are thinking of using [flash](http://guides.rubyonrails.org/action_controller_overview.html#the-flash) in which we pass the username and password as keys. We cannot get around having an intermediate page however as we can't send a direct post request. Any suggestions?

Thanks! @andrewfritz86 @sungchoi

**Comment by sungchoi** [comment]
@pppetrov 

Sessions can be accessed from any controller and are already created by Rails even before user creation or login. Hence you'll notice that you don't actually 'create' a session from the SessionsController#create action.

I would consider adding session/login/loggedin?/currentuser/etc type helper methods into the application controller and using those. 

Using the flash object is clever but very hacky.

**Comment by pppetrov** [comment]
Thanks Sung! We did it with flash, but we'll definitely go back and change it, cause we obviously don't want to be hacky (:
